# Generated by Django 4.2.15 on 2024-08-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssembleOrder",
            fields=[
                ("aid", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=30)),
                ("product_number", models.CharField(max_length=30)),
                ("erp_code", models.CharField(max_length=30)),
                ("product_count", models.IntegerField()),
                ("working_num", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=20)),
                ("worker", models.CharField(max_length=100)),
                ("orderdate", models.DateTimeField(db_column="orderDate")),
                ("defectcount", models.IntegerField(db_column="defectCount")),
                ("stock", models.IntegerField()),
                ("completedate", models.DateField(db_column="completeDate")),
                ("using_part", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "assemble_order",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InjectionSchedule",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("injector", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "day_or_night",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("division", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("erp_code", models.CharField(blank=True, max_length=100, null=True)),
                ("work_date", models.DateField(blank=True, null=True)),
                ("scheduling_datetime", models.DateTimeField(blank=True, null=True)),
                ("order_count", models.IntegerField(blank=True, null=True)),
                ("injection_count", models.IntegerField(blank=True, null=True)),
                ("defect_count", models.IntegerField(blank=True, null=True)),
                ("mold_num", models.CharField(blank=True, max_length=100, null=True)),
                ("is_ordered", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mold_erp_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "working_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "worker_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_injected",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("production_box_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "injection_schedule",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="AccountTest",
        ),
        migrations.DeleteModel(
            name="Assemble",
        ),
        migrations.DeleteModel(
            name="Bom",
        ),
        migrations.DeleteModel(
            name="Bom2",
        ),
        migrations.DeleteModel(
            name="Bom2Backup",
        ),
        migrations.DeleteModel(
            name="BomExample",
        ),
        migrations.DeleteModel(
            name="Currentdefectlist",
        ),
        migrations.DeleteModel(
            name="Currenthalfassemblestock",
        ),
        migrations.DeleteModel(
            name="Currentpackingwaitstock",
        ),
        migrations.DeleteModel(
            name="CurrentPrimaryMaterialStock",
        ),
        migrations.DeleteModel(
            name="CustomerQuality",
        ),
        migrations.DeleteModel(
            name="CustomerQualityProductData",
        ),
        migrations.DeleteModel(
            name="Defect",
        ),
        migrations.DeleteModel(
            name="DefectLog",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Facility",
        ),
        migrations.DeleteModel(
            name="FacilityHistory",
        ),
        migrations.DeleteModel(
            name="FacilityTest",
        ),
        migrations.DeleteModel(
            name="FactoryTest",
        ),
        migrations.DeleteModel(
            name="Inputfaultycreate",
        ),
        migrations.DeleteModel(
            name="Inputfaultyinspection",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ItemBackup",
        ),
        migrations.DeleteModel(
            name="ItemMaterial",
        ),
        migrations.DeleteModel(
            name="ItemMaterialBackup",
        ),
        migrations.DeleteModel(
            name="ItemPrimaryMaterial",
        ),
        migrations.DeleteModel(
            name="ItemPrimaryMaterialBackup",
        ),
        migrations.DeleteModel(
            name="LoginLog",
        ),
        migrations.DeleteModel(
            name="Lv2Assembly",
        ),
        migrations.DeleteModel(
            name="Management",
        ),
        migrations.DeleteModel(
            name="MassTestingInspection",
        ),
        migrations.DeleteModel(
            name="MassTestingStandard",
        ),
        migrations.DeleteModel(
            name="MassTestingStandardImg",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="MemberOldVersion",
        ),
        migrations.DeleteModel(
            name="Mold",
        ),
        migrations.DeleteModel(
            name="MoldHistory",
        ),
        migrations.DeleteModel(
            name="MoldTest",
        ),
        migrations.DeleteModel(
            name="MoldTest1",
        ),
        migrations.DeleteModel(
            name="MoldTest1Backup",
        ),
        migrations.DeleteModel(
            name="Packaging",
        ),
        migrations.DeleteModel(
            name="PackagingTest",
        ),
        migrations.DeleteModel(
            name="Packing",
        ),
        migrations.DeleteModel(
            name="PartsManagement",
        ),
        migrations.DeleteModel(
            name="PdfHomeDirectory",
        ),
        migrations.DeleteModel(
            name="PerformanceTest",
        ),
        migrations.DeleteModel(
            name="PopImg",
        ),
        migrations.DeleteModel(
            name="PrimaryMaterialWarehouse",
        ),
        migrations.DeleteModel(
            name="PrimaryMaterialWarehousing",
        ),
        migrations.DeleteModel(
            name="QualityManage",
        ),
        migrations.DeleteModel(
            name="RequiredAmountCheck",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="ScheduleTest",
        ),
        migrations.DeleteModel(
            name="Seojinmodbus",
        ),
        migrations.DeleteModel(
            name="Shipmentcomplete",
        ),
        migrations.DeleteModel(
            name="ShipmentcompleteTest",
        ),
        migrations.DeleteModel(
            name="Shipmentinspection",
        ),
        migrations.DeleteModel(
            name="ShipmentinspectionTest",
        ),
        migrations.DeleteModel(
            name="ShipmentWarehouse",
        ),
        migrations.DeleteModel(
            name="StorageTest",
        ),
        migrations.DeleteModel(
            name="Usingstocktoinspection",
        ),
        migrations.DeleteModel(
            name="Usingstocktoschedule",
        ),
        migrations.DeleteModel(
            name="Warehouse",
        ),
        migrations.DeleteModel(
            name="Warehousing",
        ),
        migrations.DeleteModel(
            name="WarehousingTest",
        ),
        migrations.DeleteModel(
            name="Worker",
        ),
        migrations.DeleteModel(
            name="WorkOrder",
        ),
        migrations.AlterModelTable(
            name="currentassemblestock",
            table="current_assemble_stock",
        ),
        migrations.AlterModelTable(
            name="currentpartstock",
            table="current_part_stock",
        ),
    ]
