version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env # 외부 DB 설정 포함
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80" # 외부에서 접근 가능한 포트 설정
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
